[package]
name = "ftp-rustified"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.38.0", features = ["full"] }
chrono = "0.4.0"
serde = { version = "1.0.210", features = ["derive"] }